# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5667947100c3b816669c50e143774d4dfd34d75c138625c0616bd8ec4dd9e414ed5a549f47e4a5f0d0cc1c634811d3b0e6735814fe25558dce92587f91a589af

test:
  secret_key_base: 73bfa1bac512954af91f8951cf4a98e024c194bbf784513527fef5157fcd88b4e9b12c5c1af6201905f62019491c947ab9a5af4ba11dc1896510b7532f940c61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 943801b9fccd2f90cc02b54ff1b8d52a4bd73e44cd77240de15917a046f04600ee52d0a854fe1467784838f3113dcf0138a0dd2ace6f7b209b61311e793ad90d
